// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hpaptqudnjycydruqdpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwYXB0cXVkbmp5Y3lkcnVxZHB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMDg2MjEsImV4cCI6MjA3Njc4NDYyMX0.pSUTteRIq9_Il4rivpEKKRi5TrvL2f2MDWmGC_MAkOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);